### ISSUE TITLE
DeAddonify the library if possible (v1.1.0)

### ISSUE THREAD

**Issue by BJTMastermind** [BJTMastermind/MCBE-Dynamic-Data-Storage#8]
If possible remove all files related to Minecraft bedrock addons.

this could create an issue where the structure file needed to place the shulker boxes can't be found.

but this would also make the library cleaner if it does work.

**Comment by VoxelBill** [comment]
Looks like libraries might not be possible for the scripting api based on my testing. I have also tried other community libraries made for the scripting api but they don't seem to load either. on a side note doesn't look like even in behavior pack form that this library works so some things might need to be adjusted for that to work right unless im not adding this correctly as a dependency.

**Comment by VoxelBill** [comment]
looks like a possible way to get this to work is using `esbuild` which would merge the library with the project your using it in. this also means that the `esbuild` part will need to be done on the user of the libraries end so added intructions would need to be added into the README for that. Will do some testing to see how this works.

**Comment by VoxelBill** [comment]
`esbuild` is a success! but currently requires the library to be installed as a behavior pack as well due to the need of the structure file. So i will likely swap out the shulker boxes for barrels or something else so thats not needed, although they wont blend in with the bedrock that well like the shulker boxes do.

**Comment by VoxelBill** [comment]
version 1.1.0 is now 95% complete, only thing remaining is the updated README.md file.

**Comment by VoxelBill** [comment]
Completed
